# Generated by Django 4.0.6 on 2022-08-03 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=20)),
                ('dtTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('localId', models.IntegerField()),
            ],
        ),
    ]
